kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/volumes/postgresql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
