{
 "title": "PostgreSQL Custom Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Common Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cache Usage, [%]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit) / (sum(pg_stat_database_blks_hit) + sum(pg_stat_database_blks_read)),0.1)"
    }
   ]
  },
  {
   "title": "Transactions, [transaction/sec]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_database_xact_rollback[1m])) + sum(rate(pg_stat_database_xact_commit[1m])))/60"
    }
   ]
  },
  {
   "title": "Transactions, [idle]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction\"})"
    }
   ]
  },
  {
   "title": "Queries, [query/sec]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls[1m]))/60"
    }
   ]
  },
  {
   "title": "Sessions, [active]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Sessions, [idle]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"})"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_in_bytes{datname!~\"template.*\", datname!~\"postgres\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "Connections" }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average CPU Usage, [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m])) * 100",
     "legendFormat": "Postgres CPU Info"
    }
   ]
  },
  {
   "title": "Average Memory Usage, [MB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes[5m]) * 0.000001)",
     "legendFormat": "Postgres Mem Info"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]) * 0.000001)",
     "legendFormat": "Postgres Virtual Mem Info"
    }
   ]
  },
  {
   "title": "Average Disk Read/Write, [MiB/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total[5m]) * 0.000001)",
     "legendFormat": "Node Read"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total[5m]) * 0.000001)",
     "legendFormat": "Node Write"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Top-5 long queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, pg_stat_statements_mean_time_seconds{datname!~\"template.*\", datname!~\"postgres\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_custom_activity_runtime{datname!~\"template.*\", datname!~\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched[5m]) > 1000",
       "legendFormat": "{{datname}} SELECT (index scan)"
      },
      {
       "expr": "rate(pg_stat_database_tup_returned[5m]) > 1000",
       "legendFormat": "{{datname}} SELECT (table scan)"
      }
     ]
    },
    {
     "title": "Insert",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted[5m]) > 0",
       "legendFormat": "{{datname}} INSERT"
      }
     ]
    },
    {
     "title": "Update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_updated[5m]) > 0",
       "legendFormat": "{{datname}} UPDATE"
      }
     ]
    },
    {
     "title": "Delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_deleted[5m]) > 0",
       "legendFormat": "{{datname}} DELETE"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts / Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "pg_locks_count{datname!~\"template.*\", datname!~\"postgres\"} > 0",
       "legendFormat": "{{datname}} {{mode}}"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_conflicts{datname!~\"template.*\", datname!~\"postgres\"}[5m]) > 0",
       "legendFormat": "{{datname}} conflicts"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_deadlocks{datname!~\"template.*\", datname!~\"postgres\"}[5m]) > 0",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname!~\"template.*\", datname!~\"postgres\", datid!~\"0\"}[5m]) > 1",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Rollbacks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_rollback{datname!~\"template.*\", datname!~\"postgres\", datid!~\"0\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Longest",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration{datname!~\"template.*\", datname!~\"postgres\", datid!~\"0\"} > 0",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  }
 ]
}