- name: Prepare Node
  tags: prepare_node
  
  block:
    - name: Disable SWAP
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Create Keyrings folder
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Create an empty file for custom-modules
      copy:
        content: ""
        dest: /etc/modules-load.d/99-custom-modules.conf
        force: no

    - name: Change custom modules
      lineinfile:
        path: /etc/modules-load.d/99-custom-modules.conf
        line: "{{ item }}"
      with_items:
        - "overlay"
        - "br_netfilter"

    - name: Apply modules
      shell: |
        systemctl restart systemd-modules-load.service

    - name: Create an empty file for custom-sysctl
      copy:
        content: ""
        dest: /etc/sysctl.d/99-custom-sysctl.conf
        force: no

    - name: Change custom-sysctl
      lineinfile:
        path: /etc/sysctl.d/99-custom-sysctl.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.ipv4.tcp_tw_reuse = 1"
        - "net.ipv4.ip_local_port_range = 1024 65535"
        - "net.core.somaxconn = 65535"
        - "net.ipv4.ip_forward = 1"
        - "net.core.default_qdisc = fq"
        - "net.ipv4.tcp_congestion_control = bbr"

    - name: Apply sysctl
      shell: |
        sysctl --system

    - name: Set UTC timezone
      shell: |
        cp /usr/share/zoneinfo/UTC /etc/localtime

    - name: Set UTF8 Locale
      shell: |
        cat << EOF | sudo tee  /etc/default/locale
        LANG="en_US.utf8"
        LANGUAGE="en_US.utf8"
        LC_ALL="en_US.utf8"
        EOF

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
          - lsb-release
          - ca-certificates
          - git
        state: present
