apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $CERT_MANAGER_EMAIL
    privateKeySecretRef:
      name: cert-cluster-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              metadata:
              spec:
                nodeSelector:
                  kubernetes.io/hostname: $MASTER_NODE_NAME
