kind: Service
apiVersion: v1
metadata:
 name: postgres-external
spec:
 ports:
 - port: 5432
   targetPort: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
 name: postgres-external
subsets:
 - addresses:
     - ip: ${ip_сервер_с_бд}
   ports:
     - port: ${порт_бд}
