version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
